name: Issue Auto Commenter
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Debug info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repo: ${{ github.event.repository.name }}"

      - name: Add comment to new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = 'abhisek247767';
            const repo = 'LeetCode2024-6Companies30Days';
            const issue_number = context.issue.number;
            
            console.log(`Attempting to comment on issue ${issue_number} in ${owner}/${repo}`);
            
            try {
              const result = await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                body: '👋 Thanks for opening this issue! We appreciate your feedback and will look into it as soon as possible.'
              });
              console.log('Comment added successfully. Response:', JSON.stringify(result, null, 2));
            } catch (error) {
              console.error('Error adding comment:', error);
              console.error('Error details:', JSON.stringify(error, null, 2));
              core.setFailed(`Action failed with error: ${error.message}`);
            }
