name: Issue Auto Commenter
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Debug info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repo: ${{ github.event.repository.name }}"

      - name: Add comment to new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.name;
            const issue_number = context.issue.number;
            
            console.log(`Attempting to comment on issue ${issue_number} in ${owner}/${repo}`);
            
            try {
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                body: '👋 Thanks for opening this issue! We appreciate your feedback and will look into it as soon as possible.'
              });
              console.log('Comment added successfully');
            } catch (error) {
              console.error('Error adding comment:', error);
              core.setFailed(`Action failed with error: ${error}`);
            }
